apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-k8s-java-app-deployment
  labels:
    app: devops-k8s-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-k8s-java-app
  template:
    metadata:
      labels:
        app: devops-k8s-java-app
    spec:
      containers:
        - name: devops-k8s-java-app
          image: aniljagari/devops-k8s-java-complete-ci-cd:latest
          ports:
            - containerPort: 8080
