apiVersion: v1
kind: Service
metadata:
  name: devops-k8s-java-app-service
spec:
  selector:
    app: devops-k8s-java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
